name: rocket_apps_mvvm
description: A straith to the point mvvm framework for Flutter

publish_to: 'none'

version: 0.3.2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
